### ISSUE TITLE
Rebate different from 0

### ISSUE THREAD

**Issue by Tempesta1200** [RomanMichaelPaolucci/Simulating_Financial_Options#1]
Hi Roman, if my option have a rebate different from 0 what i have to do in the code to reflect the rebate?
Thanks

**Comment by romanmichaelpaolucci** [comment]
Hey there,

I would advise using the stochastic process simulation module in the library QFin.  This will allow you to develop your own nonzero rebate case in developing your risk neutral expectation for price.

Cheers,
Roman
